#!/bin/sh

cd ~

sudo apt-get update -y
sudo apt-get upgrade -y

sudo mkdir download
#Download cwagent installer & cwagent config file
cd download
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb \
    -o ~/download/amazon-cloudwatch-agent.deb

wget https://raw.githubusercontent.com/NUS-Korea-Society/nuskusa-infra-tf/main/scaling/templates/config.json

#Depackage cwagent
sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

#Clone backend file
cd ..
sudo git clone "https://github.com/NUS-Korea-Society/nuskusa-infra.git"

#Run cwagent
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:nuskusa_infra/.cwagent/config.json

#Run Backends
cd nuskusa-infra
docker compose up -d
