variable "bucket" {}
variable "vpc_backend_key" {}
variable "region" {}
variable "ami_filters" {}
variable "keyname" {}
variable "public_key" {}
variable "instance_type" {}
variable "monitoring" {}
variable "root_block_device" {}
